### ISSUE TITLE
MxNet build?

### ISSUE THREAD

**Issue by deepakkumar1984** [kevmal/MXNetSharp#46]
How to get the mxnet library dll, do you have the build for 1.5.1 both CPU and GPU

**Comment by kevmal** [comment]
No build of libmxnet is distributed by this project. Between cuda-version, MKL-DNN and OS there's too many variations to maintain especially considering I'm most likely the only user at the moment. Easiest is (from the official [MXNet get started page](https://mxnet.apache.org/get_started?version=v1.5.1&platform=linux&language=python&environ=pip&processor=gpu)) just `pip install <mxnet flavor>`, if pip is not available the next easiest is download the whl archive and extract the relevant libs (pretty much all the none .py files in `mxnetpkg.whl/mxnet/`). Finally, the most flexible and best for serious use would obviously be to [build from source](https://mxnet.apache.org/get_started/build_from_source) with the desired options.

The specific version isn't a huge concern it will just affect the available operators. The current master has ops generated off of libmxnet b20191125 since I wanted to use the einsum operator. 1.5.1 still works but the einsum operator [(among a hand full of others)](https://cwiki.apache.org/confluence/display/MXNET/1.6.0+Release+notes#id-1.6.0Releasenotes-Newoperators) would be visible but not available.

**Comment by deepakkumar1984** [comment]
Thanks...
